on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    uses: gardenlinux/package-build/.github/workflows/build.yml@916cd324baae77b074f783e8acd145c033140a00 # main
    with:
      release: ${{ github.ref == 'refs/heads/main' }}
      arch: '["amd64"]'
