on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    uses: gardenlinux/package-build/.github/workflows/build.yml@c721cec9a0210475a38460e2b974a2984a84f901 # main
    with:
      release: ${{ github.ref == 'refs/heads/main' }}
      arch: '["amd64"]'
