on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    uses: gardenlinux/package-build/.github/workflows/build.yml@bd7d5cc46ce721a076727db145cbee3a2e5257ea # main
    with:
      release: ${{ github.ref == 'refs/heads/main' }}
      arch: '["amd64"]'
